export default {
  categories: [
    {path: 'intro', label: {en: 'intro', cn: '认识SEIN.JS'}},
    {path: 'architecture', label: {en: 'architecture', cn: '游戏框架'}},
    {path: 'functions', label: {en: 'functions', cn: '常用功能'}},
    {path: 'event', label: {en: 'event', cn: '事件系统'}},
    {path: 'resource', label: {en: 'resource', cn: '资源系统'}},
    {path: 'exception', label: {en: 'exception', cn: '异常系统'}},
    {path: 'render', label: {en: 'render', cn: '渲染系统'}},
    {path: 'basic-components', label: {en: 'basic-components', cn: '内置基础组件'}},
    {path: 'animation', label: {en: 'animation', cn: '动画系统'}},
    {path: 'physic', label: {en: 'physic', cn: '物理系统'}},
    {path: 'player', label: {en: 'player', cn: '玩家系统'}},
    {path: 'scene-editor', label: {en: 'scene-editor', cn: '场景编辑器'}},
    {path: 'extension', label: {en: 'extension', cn: '扩展系统'}},
    {path: 'optimizing', label: {en: 'optimizing', cn: '优化指南'}}
  ],
  intro: [
    {path: 'overview', label: {en: 'overview', cn: '概览'}},
    {path: 'workflow', label: {en: 'workflow', cn: '开发体系'}},
    {path: 'hello-world', label: {en: 'hello-world', cn: 'Hello, world'}},
  ],
  architecture: [
    {path: 'architecture', label: {en: 'architecture', cn: '整体架构'}},
    {path: 'engine-game-world-level', label: {en: 'engine-game-world-level', cn: '引擎、游戏、世界和关卡'}},
    {path: 'actor-component', label: {en: 'actor-component', cn: 'Actor和Component'}},
    {path: 'scene-component-actor', label: {en: 'scene-component-actor', cn: 'SceneComponent(Actor)'}},
    {path: 'info-actor', label: {en: 'info-actor', cn: 'InfoActor'}},
    {path: 'gameplay', label: {en: 'gameplay', cn: '玩法逻辑'}},
    {path: 'life-cycle', label: {en: 'life-cycle', cn: '附录：生命周期'}},
  ],
  functions: [
    {path: 'search', label: {en: 'search', cn: '归类和搜索'}},
    {path: 'predicate', label: {en: 'predicate', cn: '判断实例类型'}},
  ],
  event: [
    {path: 'manager', label: {en: 'manager', cn: '事件管理器'}},
    {path: 'trigger', label: {en: 'trigger', cn: '事件触发器'}},
    {path: 'global-events', label: {en: 'global-events', cn: '全局默认事件'}},
    {path: 'hid', label: {en: 'hid', cn: 'HID'}},
  ],
  resource: [
    {path: 'manager', label: {en: 'manager', cn: '资源管理器'}},
    {path: 'loader', label: {en: 'loader', cn: '资源加载器'}},
    {path: 'global-loaders', label: {en: 'global-loaders', cn: '全局默认加载器'}},
  ],
  exception: [
    {path: 'exception', label: {en: 'exception', cn: '异常系统'}}
  ],
  'basic-components': [
    {path: 'camera', label: {en: 'camera', cn: '摄像机和天空盒'}},
    {path: 'bsp', label: {en: 'bsp', cn: '基本几何体'}},
    {path: 'light', label: {en: 'light', cn: '灯光'}},
    {path: 'primitive', label: {en: 'primitive', cn: '图元组件'}},
    {path: 'sprite', label: {en: 'sprite', cn: '2D精灵'}},
    {path: 'timer', label: {en: 'timer', cn: '定时器'}}
  ],
  render: [
    {path: 'render-engine', label: {en: 'render-engine', cn: '渲染引擎'}},
    {path: 'texture', label: {en: 'texture', cn: '纹理'}},
    {path: 'atlas', label: {en: 'atlas', cn: '图集'}},
    {path: 'geometry', label: {en: 'geometry', cn: '几何体'}},
    {path: 'material', label: {en: 'material', cn: '材质'}},
    {path: 'render-system-actor', label: {en: 'render-system-actor', cn: 'RenderSystemActor'}},
  ],
  animation: [
    {path: 'macro', label: {en: 'macro', cn: '宏观动画'}},
    {path: 'component', label: {en: 'component', cn: '动画组件'}},
    {path: 'clip', label: {en: 'clip', cn: '动画片段'}},
  ],
  physic: [
    {path: 'physic-world', label: {en: 'physic-world', cn: '物理世界'}},
    {path: 'rigidbody', label: {en: 'rigidbody', cn: '刚体'}},
    {path: 'collider', label: {en: 'collider', cn: '碰撞体'}},
    {path: 'joint', label: {en: 'joint', cn: '关节'}},
    {path: 'event', label: {en: 'event', cn: '事件'}},
    {path: 'pick', label: {en: 'pick', cn: '拾取'}},
  ],
  player: [
    {path: 'mvc', label: {en: 'mvc', cn: 'MVC体系'}},
    {path: 'player', label: {en: 'player', cn: '玩家'}},
    {path: 'ai-fms', label: {en: 'ai-fms', cn: 'AI和状态机'}},
  ],
  'scene-editor': [
    {path: 'gltf', label: {en: 'gltf', cn: 'glTF和实例化'}},
    {path: 'unity-extension', label: {en: 'unity-extension', cn: 'Unity扩展'}},
    {path: 'export', label: {en: 'export', cn: '导出glTF'}},
    {path: 'import', label: {en: 'import', cn: '导入glTF'}},
    {path: 'gltf-extension-official', label: {en: 'gltf-extension-official', cn: 'SEIN官方特性支持'}},
    {path: 'material-sein', label: {en: 'material-sein', cn: 'SeinPBR标准材质'}},
    {path: 'material-basic', label: {en: 'material-basic', cn: 'SeinBasic材质'}},
    {path: 'atlas-sprite', label: {en: 'atlas-sprite', cn: '使用图集和精灵'}},
    {path: 'baking', label: {en: 'baking', cn: '烘焙'}},
    {path: 'script-binding', label: {en: 'script-binding', cn: '逻辑脚本绑定'}},
    {path: 'material-extension', label: {en: 'material-extension', cn: '自定义材质'}},
    {path: 'gltf-extension-custom', label: {en: 'gltf-extension-custom', cn: '自定义glTF扩展'}},
  ],
  extension: [
    {path: 'extension', label: {en: 'extension', cn: '如何编写扩展'}},
    {path: 'official-extensions', label: {en: 'official-extensions', cn: '官方扩展'}},
  ],
  optimizing: [
    {path: 'start', label: {en: 'start', cn: '寻找瓶颈'}},
    {path: 'memory', label: {en: 'memory', cn: '传输体积和内存优化'}},
    {path: 'cpu', label: {en: 'cpu', cn: 'CPU性能优化'}},
    {path: 'gpu', label: {en: 'gpu', cn: 'GPU性能优化'}},
    {path: 'data', label: {en: 'data', cn: '数据'}},
  ],
}
